Testing tests
camelCaseCrew/itu_predictive_maintenance pull request #5
Opened 2023-03-17 11:05 UTC by adamjhr

Do not merge

2023-03-21 14:09 UTC, Day0r requested changes
Please check the comments :)
Other than that, lgtm!

2023-03-21 14:09 UTC, DanyalYor commented on docker/grafana/alerting/1/__default__.tmpl
Is this an automatically generated file? Can we have it excluded from the repo?

2023-03-21 14:09 UTC, DanyalYor commented on docker/docker-compose.yaml
Why are we having a dedicated Dockerfile for grafana that just builds an image already available on the hub?

2023-03-21 14:09 UTC, Day0r commented on docker/docker-compose.yaml
The same can be said about prometheus, but here we have a volume binding. Can this also not just be part of the docker compose specification?

2023-03-21 19:41 UTC, jfho commented on docker/grafana/alerting/1/__default__.tmpl
Seems so, I'll add it to the .gitignore

2023-03-21 19:58 UTC, jfho commented on docker/docker-compose.yaml
Yes, they should be able to run without their own Dockerfiles, seems like we can have most settings in the docker compose instead.

2023-03-22 10:31 UTC, DanyalYor approved these changes

2023-03-22 10:31 UTC, merged